### ISSUE TITLE
Variable Error Spigot 1.8.7

### ISSUE THREAD

**Issue by ACMESoftCorporation** [games647/ScoreboardStats#60]
This plugin was working perfectly until I used the %money% variable.
I have Vault and Essentials Economy 1.8.
```
Scoreboard:
  Title: '&1&lQuick Stats'
  # seconds
  # For instant updates you can or 1 and it will update every second
  Update-delay: 0
  Items:
    # The Title must have under 48 characters
    # Title: Type
    '&9Online players: ' : '%online%'
    '&9You have ': '$%money%'
```
The console tells me 'the variable '§9You have' has to contains a % at the beginning and one at the end.'
